### ISSUE TITLE
Convert _posts to pages

### ISSUE THREAD

**Issue by ottok** [Seravo/docs#59]
E.g.  `_posts/<date>_<pagename>` to eg. `category/something/feature.md`

This would be a cleaner structure. Current date based blog stucture is useless in the seravo.com/docs documentation reference.

**Comment by sjaks** [comment]
So we would like to move from Jekyll posts to pages because posts have an unnecessary date attributes and messy filenames.

I have taken a deep look into a Jekyll "page" and whether it supports everything we currently have. They seem to but there are some things to take into consideration; docs currently rely on "post category" attribute and because pages cannot be assigned into a category, it's not possible to query for all pages in certain category. Also, more notably, URLs to pages are generated based with `permalink: /:categories/:title/` and we want to keep this after the move to pages.

[Jekyll collections](https://jekyllrb.com/docs/collections/) promises to provide some level of collection of similar data into same place. This might work for this.
